# Generated by Django 3.2.9 on 2021-11-18 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizz_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.today, verbose_name='date published')),
            ],
        ),
    ]
