# Generated by Django 3.2.9 on 2021-11-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_quizz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quizz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.quizz'),
        ),
    ]
