# Generated by Django 3.2.9 on 2021-11-18 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_quizz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizz',
            options={'verbose_name': 'Quizz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='quizz',
            old_name='quizz_text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='date published'),
        ),
    ]
